### ISSUE TITLE
Add prompt=none support to the implicit flow demo

### ISSUE THREAD

**Issue by PinpointTownes** [openiddict/openiddict-samples#11]
Currently blocked by https://github.com/openiddict/openiddict-core/issues/231.

**Comment by PinpointTownes** [comment]
oidc-client now supports `id_token_hint`.

If you're interested in adding `prompt=none` support, please ping me :smile:

**Comment by shaunluttin** [comment]
I am interested in adding `prompt=none`. Storing in `localStorage` instead of `sessionStorage` is non-trivial with oidc-client-js; my sense is that that is by design (https://github.com/IdentityModel/oidc-client-js/issues/49), so in order to keep the user signed-in across tabs, it seems we need to use `prompt=none` instead.

**Comment by shaunluttin** [comment]
I am planning to implement the following procedure, though it seems odd to me. Perhaps you can suggest alternative, @PinpointTownes. 

1. The page loads. 
1. The client app checks whether sesionStorage contains a non-expired id token. 
1. If it does not, the client app initiates silentLogin request with prompt=none. 
1. The provider receives that request. 
1. If the end user is logged in, the provider responds with new token payload. 
1. If the end user is not, the provider responds with an error. 
1. The client app processes the response and proceeds appropriately. 

I think the above flow is odd,  because the client app is handling an error, if the end user is not logged in. To me that's unnatural.

**Comment by PinpointTownes** [comment]
Done: https://github.com/openiddict/openiddict-samples/commit/1fd271e6aa23ad8afb09d9cb9a422148df67d8a0

Thanks Shaun! :clap:
