### ISSUE TITLE
Add another set of samples where an ASP.NET 7 (and beyond) Auth Server supports clients of multiple vintage

### ISSUE THREAD

**Issue by dlandi** [openiddict/openiddict-samples#231]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Most of us will have an existing codebase that is still in transition from DotNet 4.7/8 to DotNet6/7.

In my case, I would like to stand up a modern Auth Server on ASP.NET 7 that connects with multiple clients from ASP.NET 4.8, ASP.NET6/7, as well as Blazor and MAUI. 

I don't see a need to provide a **server** on anything but the latest version of .NET. It is the clients that may be tied to a legacy codebase, and so we need examples of all these clients connecting to the **same** modern Auth Server.

**Comment by dlandi** [comment]
Instead of adding another issue, I'll append this one:

The Kalarba demo has an ASP.NET 4.8 OWIN Server talking to an NET7 client. In line with my comments above, this scenario should be flipped.

The server should be on the latest .NET platform, with demos coming from various client platform vintages.

**Comment by kevinchalet** [comment]
> I don't see a need to provide a server on anything but the latest version of .NET. It is the clients that may be tied to a legacy codebase, and so we need examples of all these clients connecting to the same modern Auth Server.

> The Kalarba demo has an ASP.NET 4.8 OWIN Server talking to an NET7 client. In line with my comments above, this scenario should be flipped.

While the ASP.NET Core server integration is definitely more popular than the OWIN/ASP.NET 4.x integration, it is frequently used to modernize monolithic ASP.NET apps that used `OAuthAuthorizationServerMiddleware`: it offers an easy migration path for those who want to keep their OAuth 2.0/OIDC server in their monolithic apps instead of adopting a microservice approach. It's probably not a scenario you're interested in, but it's a scenario that exists 😄 

As for adding new samples, I'm not against it, but maintaining all these samples has a cost and it's impossible to create samples for every possible combination.

**Comment by kevinchalet** [comment]
> The Kalarba demo has an ASP.NET 4.8 OWIN Server talking to an NET7 client. In line with my comments above, this scenario should be flipped.

> The server should be on the latest .NET platform, with demos coming from various client platform vintages.

`Kalarba.Client` and `Fornax.Client` now target .NET Framework 4.8 instead of .NET 8.0 (very changes are required for that, BTW, since the OpenIddict client and its system integration behaves the same way on .NET and .NET Framework).

A new `Sorgan.Console.Client` sample was added and targets .NET 8.0.
