### ISSUE TITLE
Using access_token in ng2 app example

### ISSUE THREAD

**Issue by joel00** [openiddict/openiddict-samples#38]
Should I pass the ngrx store in every service in order to use the access_token? doing something like this:

@Injectable()
export class ServiceOne extends MyService {
  access_token: string;

  constructor(private http: Http, private store: Store<AppState>) {
    super();
    store.subscribe(state => this.access_token = state.auth.authTokens.access_token);

    this._headers.append('Content-Type', 'application/json');
    this._headers.append('Authorization', 'Bearer ' + this.access_token);
.........
.......
  }

Or is there a better (simpler) way to use it?

**Comment by Toxicable** [comment]
@joel00 You're fine, that's the correct way for retrieving your access_token. However I would suggest using the `selected` operator like so `store.select(state => state.auth).first().subscribe(auth=> this.access_token = auth.authTokens.access_token);
So that it will only emit when `state.auth` changes/has a value plus it will only emit once then complete the stream

**Comment by joel00** [comment]
Thanks @Toxicable. I'll test as you suggest.
