### ISSUE TITLE
AddSigningCertificate error

### ISSUE THREAD

**Issue by BehnamAbdy** [openiddict/openiddict-samples#5]
i cloned the samples and when run the server project i get this error 
"Additional information: At least one signing key must be registered. Consider registering a X.509 certificate using 'services.AddOpenIddict().AddSigningCertificate()' or call 'services.AddOpenIddict().AddEphemeralSigningKey()' to use an ephemeral key."
do i have to do something or some extra config is missing?

**Comment by PinpointTownes** [comment]
Thanks for reporting that. It should be fixed by https://github.com/openiddict/openiddict-samples/commit/4d039822aeefee456ecf1cc82deac0bd91699297

> do i have to do something or some extra config is missing?

Yep, you must now call `AddEphemeralSigningKey()` to configure an in-memory signing key or add an explicit key using `AddSigningCertificate()`. This design change was merged last week but I forgot to update the MVC sample hosted here.

**Comment by BehnamAbdy** [comment]
thank u anyway
