### ISSUE TITLE
Question - Best way to add "Assume Identity" using OpenIddict

### ISSUE THREAD

**Issue by DuncancMartin** [openiddict/openiddict-samples#75]
We are using OpenIddict to generate tokens to authenticate users and define what modules they have access to.  Our support team would like to be able to assume the identity of the customer they are talking to in order to be able to better diagnose issues.  Is there an approved way for us to implement this?
The simplest solution would be an additional endpoint where the support user logs in and provides the username they wish to impersonate - this could then generate the token of said user (with additional properties indicating the support persons identity).
Are there any security or other considerations that mean this solution is not recommended?
Thanks
Duncan

**Comment by PinpointTownes** [comment]
While there's nothing about this scenario in the OAuth 2.0/OpenID Connect specs, it's a very frequent demand in the enterprise world.

The approach I've personally used is to rely on the standard code flow, but with a custom OIDC parameter - e.g `impersonated_username` - that can be specified by the client application (or a third party like a centralized portal: https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin) to trigger an impersonation-enabled flow.

In the authorization controller action(s), you can simply check whether the user is allowed to specify an `impersonated_username` parameter and use the identity of the impersonated user instead of the impersonator (with additional properties if you want).
