### ISSUE TITLE
Consider using Identity UI in the samples

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-samples#83]
We should consider removing the Identity controllers - scaffolded a while ago - and using the Identity UI based on Razor Pages instead.

**Comment by jeremycook** [comment]
Hey Kevin, I actually like that everything is there in the sample. It makes it all much easier to comprehend and tweak when needed. So if this were done my suggestion would be that it gets its own sample in addition to the existing Velusia sample.

**Comment by jeremycook** [comment]
BTW, I ended up over here because I'm exploring replacing IdSrv with openiddict in a project that uses ASP.NET Identity as part of upgrading from .NET Core 3.1 to .NET 5. I would use Velusia as a guide. Let me know if/how you would like the Identity UI sample to look (scaffold Identity UI Razor Pages vs. just take dependency on the RCL) and any other relevant information and I'll see if I can make a Velusia equivalent with the Identity UI that you can benefit from. Good samples are always such a big help.

**Comment by kevinchalet** [comment]
Hey @jeremycook,

When I opened this ticket, I was motivated by 2 things:
  - Removing the old membership-related controllers/views inherited from ASP.NET Core 1.x to reduce the number of files we need to maintain.
  - Making the older samples more consistent with the recent ones, that use Identity UI and its RCL-based packages.

That said, if you think it's worth keeping these artifacts, I'm not strongly against it 😃

**Comment by jeremycook** [comment]
I added the "Verkuyl" projects to a branch in my repo. They are based on Velusia but the server uses the ASP.NET Identity RCL UI. I haven't created a merge request because I'm hesitating on adding Verkuyl vs. updating Velusia. Now that I' here I think I will rename this to Velusia and submit that as a merge request. At this point Verkuyl retains everything that I found important for understanding OpenIddict: the Authorization, Userinfo and Resource controllers... So yeah, I guess I feel fine with updating Velusia with Identity UI and saying bye to the old Account and Manager controllers.

https://github.com/jeremycook/openiddict-samples/tree/verkuyl/samples/Verkuyl

**Comment by kevinchalet** [comment]
> So yeah, I guess I feel fine with updating Velusia with Identity UI and saying bye to the old Account and Manager controllers.

Great! Let's do that, then 👍🏻 

We'll probably also want to update the `Zirku.Server` sample as it also uses the good old ASP.NET Core 1.x controllers/views. Let me know if it's something you'd be interested in doing.

**Comment by jeremycook** [comment]
Once you feel good about Velusia.Server updating Zirku.Server would be straight forward.

**Comment by kevinchalet** [comment]
@jeremycook would you still be interested in updating the Zirku.Server sample? 😃

**Comment by jeremycook** [comment]
Hey @kevinchalet I don't have time right now but I've saved the GitHub notification and might work on it in the future.

For reference #124 is my merge request that updated the Velusia.Server UI
